backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: static/images
public_folder: /images

collections:
  - name: 'continents'
    label: 'Continents'
    label_singular: 'Continent'
    folder: 'src/atlas/continents'
    extension: md
    format: frontmatter
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Title (En)', name: 'titleEn', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
  - name: 'countries'
    label: 'Pays'
    folder: 'src/atlas/countries'
    extension: md
    format: frontmatter
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Title (En)', name: 'titleEn', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
