backend:
  name: git-gateway
  branch: master

collections:
  - name: 'continent'
    label: 'Continent'
    folder: 'src/atlas/continent'
    create: true
    slug: '{{titleFr}}'
    fields:
      - { label: 'Title Fr', name: 'titleFr', widget: 'string' }
      - { label: 'Title En', name: 'titleEn', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
  - name: 'country'
    label: 'Pays'
    folder: 'src/atlas/country'
    create: true
    slug: '{{titleFr}}'
    fields:
      - { label: 'Title Fr', name: 'titleFr', widget: 'string' }
      - { label: 'Title En', name: 'titleEn', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
