backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images

collections:
  - name: 'continents'
    label: 'Continents'
    label_singular: 'Continent'
    folder: 'data/continents'
    extension: yml
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Slug', name: 'title', widget: 'string' }
      - { label: 'Name (Fr)', name: 'nameFr', widget: 'string' }
      - { label: 'Name (En)', name: 'nameEn', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Année PIB',
          name: 'gdpYear',
          widget: 'number',
          valueType: 'int',
        }
      - {
          label: 'Nombre de fuseaux horaires',
          name: 'numberOfTimeZones',
          widget: 'number',
          valueType: 'int',
        }
  - name: 'subcontinents'
    label: 'Sous-continents'
    label_singular: 'Sous-continent'
    folder: 'data/subcontinents'
    extension: yml
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Slug', name: 'title', widget: 'string' }
      - { label: 'Name (Fr)', name: 'nameFr', widget: 'string' }
      - { label: 'Name (En)', name: 'nameEn', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - label: 'Continent'
        name: 'continent'
        widget: 'relation'
        collection: 'continents'
        searchFields: ['title']
        valueField: 'title'
        displayFields: ['title', 'nameFr', 'nameEn']
  - name: 'countries'
    label: 'Pays'
    folder: 'data/countries'
    extension: yml
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Slug', name: 'title', widget: 'string' }
      - { label: 'Name (Fr)', name: 'nameFr', widget: 'string' }
      - { label: 'Name (En)', name: 'nameEn', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Description (Fr)', name: 'descriptionFr', widget: 'markdown' }
      - { label: 'Description (En)', name: 'descriptionEn', widget: 'markdown' }
      - { label: 'Nom long', name: 'longName', widget: 'string' }
      - { label: 'Nom local', name: 'localeName', widget: 'string' }
      - label: 'Sous-continent'
        name: 'subcontinent'
        widget: 'relation'
        collection: 'subcontinents'
        searchFields: ['title']
        valueField: 'title'
        displayFields: ['title', 'nameFr', 'nameEn']
