backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images

collections:
  - name: 'continents'
    label: 'Continents'
    label_singular: 'Continent'
    folder: 'data/continents'
    extension: yml
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Title (En)', name: 'titleEn', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
  - name: 'subcontinents'
    label: 'Sous-continents'
    label_singular: 'Sous-continent'
    folder: 'data/subcontinents'
    extension: yml
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Title (En)', name: 'titleEn', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - label: 'Continent'
        name: 'continent'
        widget: 'relation'
        collection: 'continents'
        searchFields: ['title']
        valueField: 'title'
        displayFields: ['title']
  - name: 'countries'
    label: 'Pays'
    folder: 'data/countries'
    extension: yml
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Title (En)', name: 'titleEn', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - label: 'Sous-continent'
        name: 'subcontinent'
        widget: 'relation'
        collection: 'subcontinents'
        searchFields: ['title']
        valueField: 'title'
        displayFields: ['title']
